#!/usr/bin/env python
"""Random-initialization control for the completed LOSO few-shot experiment.

For every target and k, this script reuses the exact nested subset generated by
the transfer run and enforces the same optimizer-step budget. Every k starts
from one identical seed-controlled random model state.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import logging
import os.path as osp
import sys
from dataclasses import asdict
from pathlib import Path

import numpy as np
import torch

REPO_ROOT = osp.abspath(osp.join(osp.dirname(__file__), ".."))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

import run_multisource_loso_fewshot as transfer  # noqa: E402
from torch_geometric.graphgym.config import cfg  # noqa: E402
from torch_geometric.graphgym.model_builder import create_model  # noqa: E402
from torch_geometric.graphgym.utils.comp_budget import params_count  # noqa: E402


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def save_json(path: Path, payload) -> None:
    transfer.save_json(path, payload)


def normalizer_from_json(payload: dict) -> transfer.DomainNormalizer:
    return transfer.DomainNormalizer(
        network=str(payload["network"]),
        flow_mean=float(payload["flow_mean"]),
        flow_std=float(payload["flow_std"]),
        flow_count=int(payload["flow_count"]),
        attr_mean=tuple(float(value) for value in payload["attr_mean"]),
        attr_std=tuple(float(value) for value in payload["attr_std"]),
        attr_count=int(payload["attr_count"]),
        legacy_flow_mean=float(payload["legacy_flow_mean"]),
        legacy_flow_std=float(payload["legacy_flow_std"]),
        legacy_attr_mean=tuple(float(value) for value in payload["legacy_attr_mean"]),
        legacy_attr_std=tuple(float(value) for value in payload["legacy_attr_std"]),
        fitted_from=str(payload.get("fitted_from", "")),
    )


def assert_normalizers_match(
    fitted: transfer.DomainNormalizer,
    expected: transfer.DomainNormalizer,
) -> None:
    scalar_fields = (
        "flow_mean",
        "flow_std",
        "legacy_flow_mean",
        "legacy_flow_std",
    )
    for field in scalar_fields:
        lhs = float(getattr(fitted, field))
        rhs = float(getattr(expected, field))
        if not np.isclose(lhs, rhs, rtol=1e-10, atol=1e-8):
            raise RuntimeError(f"Normalizer mismatch for {field}: fitted={lhs}, transfer={rhs}")
    for field in ("attr_mean", "attr_std", "legacy_attr_mean", "legacy_attr_std"):
        if not np.allclose(
            np.asarray(getattr(fitted, field)),
            np.asarray(getattr(expected, field)),
            rtol=1e-10,
            atol=1e-8,
        ):
            raise RuntimeError(f"Normalizer mismatch for {field}.")


def state_dict_sha256(state_dict: dict[str, torch.Tensor]) -> str:
    digest = hashlib.sha256()
    for key in sorted(state_dict):
        value = state_dict[key].detach().cpu().contiguous()
        digest.update(key.encode("utf-8"))
        digest.update(value.numpy().tobytes())
    return digest.hexdigest()


def subset_sha256(indices: np.ndarray) -> str:
    return hashlib.sha256(np.asarray(indices, dtype=np.int64).tobytes()).hexdigest()


def protocol_signature(args: argparse.Namespace, transfer_summary: dict) -> str:
    cfg_path = Path(args.cfg).expanduser().resolve()
    payload = {
        "task": "random-init-few-shot-control-v1",
        "target": transfer.canonical_network(args.target),
        "transfer_protocol_signature": transfer_summary["protocol_signature"],
        "k_values": args.k_values,
        "adapt_epochs": args.adapt_epochs,
        "batch_size": args.batch_size,
        "adapt_lr": args.adapt_lr,
        "weight_decay": args.weight_decay,
        "grad_clip": args.grad_clip,
        "seed": args.seed,
        "cfg_sha256": hashlib.sha256(cfg_path.read_bytes()).hexdigest(),
    }
    return hashlib.sha256(json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest()[:16]


def setup_logging(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(output_dir / "random_init_fewshot.log", mode="a", encoding="utf-8"),
        ],
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cfg", default="configs/GatedGCN/network-pairs-topology.yaml")
    parser.add_argument("--data-root", default="create_sioux_data/processed_data")
    parser.add_argument("--transfer-root", default="results/multisource_loso_fewshot")
    parser.add_argument("--output-root", default="results/random_init_fewshot")
    parser.add_argument("--target", required=True, choices=tuple(transfer.NETWORKS.values()))
    parser.add_argument(
        "--k-values",
        type=int,
        nargs="+",
        default=[0, 50, 100, 250, 500, 1000, 2000, 4000],
    )
    parser.add_argument("--adapt-epochs", type=int, default=50)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--eval-batch-size", type=int, default=32)
    parser.add_argument("--adapt-lr", type=float, default=1e-4)
    parser.add_argument("--weight-decay", type=float, default=1e-5)
    parser.add_argument("--grad-clip", type=float, default=1.0)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--num-threads", type=int, default=16)
    parser.add_argument("--device", choices=("auto", "cpu", "cuda"), default="auto")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()
    args.k_values = sorted(set(int(value) for value in args.k_values))
    if not args.k_values or args.k_values[0] != 0:
        parser.error("--k-values must include 0.")
    if args.device == "cuda" and not torch.cuda.is_available():
        parser.error("--device=cuda requested but CUDA is unavailable.")
    return args


def main() -> None:
    args = parse_args()
    target = transfer.canonical_network(args.target)
    transfer_dir = Path(args.transfer_root).expanduser().resolve() / f"target_{target.lower()}"
    transfer_summary_path = transfer_dir / "summary.json"
    normalizer_path = transfer_dir / "input_only_normalizers.json"
    nested_path = transfer_dir / "fewshot_nested_indices.npz"
    for required in (transfer_summary_path, normalizer_path, nested_path):
        if not required.exists():
            raise FileNotFoundError(f"Required completed transfer artifact is missing: {required}")

    transfer_summary = load_json(transfer_summary_path)
    if list(args.k_values) != [int(value) for value in transfer_summary["k_values"]]:
        raise RuntimeError(
            f"Random baseline k-values {args.k_values} do not match transfer k-values "
            f"{transfer_summary['k_values']}."
        )
    signature = protocol_signature(args, transfer_summary)
    args.protocol_signature = signature
    output_dir = Path(args.output_root).expanduser().resolve() / f"target_{target.lower()}"
    setup_logging(output_dir)
    final_path = output_dir / "summary.json"
    if final_path.exists() and not args.overwrite:
        existing = load_json(final_path)
        if existing.get("protocol_signature") == signature:
            logging.info("Completed random-init baseline already exists; skipping %s", final_path)
            return
        raise RuntimeError(f"Protocol mismatch in existing summary: {final_path}")

    transfer_normalizers = load_json(normalizer_path)["normalizers"]
    expected_normalizer = normalizer_from_json(transfer_normalizers[target])
    dataset_dir = transfer.dataset_dir_for(Path(args.data_root).expanduser().resolve(), target)
    train_data = transfer.load_split(dataset_dir, "train")
    legacy_attr, legacy_flow = transfer.load_legacy_scalers(dataset_dir)
    fitted_normalizer = transfer.fit_input_only_normalizer(
        target,
        train_data,
        legacy_attr,
        legacy_flow,
    )
    assert_normalizers_match(fitted_normalizer, expected_normalizer)
    transfer.renormalize_split(train_data, expected_normalizer)
    test_data = transfer.load_split(dataset_dir, "test")
    transfer.renormalize_split(test_data, expected_normalizer)

    nested_order = np.load(nested_path)["order"].astype(np.int64)
    if nested_order.size != len(train_data) or np.unique(nested_order).size != len(train_data):
        raise RuntimeError("Transfer nested-index file is not a permutation of the target train split.")
    if max(args.k_values) > len(train_data):
        raise ValueError(f"Requested k={max(args.k_values)}, target train size={len(train_data)}")

    transfer.set_seed(args.seed)
    transfer.configure_graphgym(args, expected_normalizer)
    # The shared adaptation routine uses this only as a GraphGym epoch fallback.
    args.source_epochs = int(getattr(cfg.optim, "max_epoch", 200))
    device = torch.device("cuda" if cfg.accelerator == "cuda" else "cpu")
    if args.device == "cuda":
        device = torch.device("cuda")
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True

    model = create_model().to(device)
    cfg.params = params_count(model)
    transfer.activate_domain(model, expected_normalizer, target)
    initial_state = copy.deepcopy(model.state_dict())
    initial_hash = state_dict_sha256(initial_state)
    torch.save(
        {
            "protocol_signature": signature,
            "model_state": initial_state,
            "initial_state_sha256": initial_hash,
            "seed": int(args.seed),
            "target": target,
        },
        output_dir / "random_initialization.ckpt",
    )

    test_loader = transfer.make_loader(
        test_data,
        args.eval_batch_size,
        shuffle=False,
        seed=args.seed,
        pin_memory=device.type == "cuda",
    )
    k_results = {}
    for k in args.k_values:
        result_path = output_dir / f"random_init_k{k:04d}.json"
        if result_path.exists() and not args.overwrite:
            existing = load_json(result_path)
            if existing.get("protocol_signature") == signature:
                k_results[str(k)] = existing
                logging.info("Reusing completed random-init k=%d", k)
                continue
            raise RuntimeError(f"Protocol mismatch in existing result: {result_path}")

        model.load_state_dict(initial_state, strict=True)
        model.to(device)
        selected_indices = nested_order[:k]
        adaptation = None
        expected_steps = 0
        if k > 0:
            transfer_adaptation = transfer_summary["k_results"][str(k)]["adaptation"]
            if transfer_adaptation is None:
                raise RuntimeError(f"Transfer result k={k} has no adaptation metadata.")
            expected_steps = int(transfer_adaptation["optimizer_steps"])
            if int(transfer_adaptation["epochs"]) != int(args.adapt_epochs):
                raise RuntimeError(
                    f"Adapt epochs mismatch at k={k}: transfer={transfer_adaptation['epochs']}, "
                    f"random={args.adapt_epochs}"
                )
            subset = [train_data[int(index)] for index in selected_indices]
            adaptation = transfer.fine_tune_target(
                model,
                subset,
                expected_normalizer,
                target,
                args,
                device,
                seed_offset=k,
            )
            if int(adaptation["optimizer_steps"]) != expected_steps:
                raise RuntimeError(
                    f"Optimizer-step mismatch at k={k}: transfer={expected_steps}, "
                    f"random={adaptation['optimizer_steps']}"
                )

        evaluation = transfer.evaluate(
            model,
            test_loader,
            expected_normalizer,
            target,
            device,
        )
        result = {
            "task": "random-init-few-shot-control",
            "protocol_signature": signature,
            "transfer_protocol_signature": transfer_summary["protocol_signature"],
            "target": target,
            "k": int(k),
            "subset_sha256": subset_sha256(selected_indices),
            "random_initial_state_sha256": initial_hash,
            "same_subset_as_transfer": True,
            "expected_transfer_optimizer_steps": int(expected_steps),
            "adaptation": adaptation,
            "test": evaluation,
        }
        save_json(result_path, result)
        k_results[str(k)] = result

    final = {
        "task": "random-init-few-shot-control",
        "protocol_signature": signature,
        "transfer_protocol_signature": transfer_summary["protocol_signature"],
        "target": target,
        "k_values": args.k_values,
        "seed": int(args.seed),
        "repeat_count": 1,
        "random_initial_state_sha256": initial_hash,
        "same_target_normalizer": True,
        "same_nested_subsets": True,
        "same_optimizer_steps": True,
        "normalizer": asdict(expected_normalizer),
        "num_parameters": int(cfg.params),
        "k_results": k_results,
    }
    save_json(final_path, final)
    logging.info("Completed random-init control for %s: %s", target, final_path)


if __name__ == "__main__":
    main()
